export interface Car {
  make: string;
  model: string;
  year: number;
  fuel: string;
  transmission: string;
  seats: number;
  class: "sedan" | "suv" | "hatchback" | "electric";
  fuelEconomy: string;
  drive: string;
  images: {
    main: string;
  };
  horsepower: string;
  torque: string;
  bootSpace: string;
  length: string;
  width: string;
  airbags: number;
  abs: boolean;
  fuelTankCapacity: string;
  acceleration: string;
}

export const cars: Car[] = [
  {
    make: "Perodua",
    model: "Myvi",
    year: 2022,
    fuel: "petrol",
    transmission: "Automatic",
    seats: 5,
    class: "hatchback",
    fuelEconomy: "4.7 L/100 km",
    drive: "fwd",
    images: { main: "/cars/perodua-myvi/main.png" },
    horsepower: "98 hp",
    torque: "133 Nm",
    bootSpace: "208 L",
    length: "3695 mm",
    width: "1695 mm",
    airbags: 2,
    abs: true,
    fuelTankCapacity: "36 L",
    acceleration: "12.5 s",
  },
  {
    make: "Perodua",
    model: "Axia",
    year: 2025,
    fuel: "petrol",
    transmission: "Automatic",
    seats: 5,
    class: "hatchback",
    fuelEconomy: "5.0 L/100 km",
    drive: "fwd",
    images: { main: "/cars/perodua-axia/main.png" },
    horsepower: "67 hp",
    torque: "91 Nm",
    bootSpace: "260 L",
    length: "3640 mm",
    width: "1600 mm",
    airbags: 2,
    abs: true,
    fuelTankCapacity: "35 L",
    acceleration: "15.5 s",
  },

  {
    make: "Proton",
    model: "Saga",
    year: 2023,
    fuel: "petrol",
    transmission: "Automatic",
    seats: 5,
    class: "sedan",
    fuelEconomy: "5.8 L/100 km",
    drive: "fwd",
    images: { main: "/cars/proton-saga/main.png" },
    horsepower: "95 hp",
    torque: "120 Nm",
    bootSpace: "420 L",
    length: "4331 mm",
    width: "1689 mm",
    airbags: 2,
    abs: true,
    fuelTankCapacity: "45 L",
    acceleration: "12.0 s",
  },
  {
    make: "Proton",
    model: "X50",
    year: 2022,
    fuel: "petrol",
    transmission: "Automatic",
    seats: 5,
    class: "suv",
    fuelEconomy: "6.5 L/100 km",
    drive: "fwd",
    images: { main: "/cars/proton-x50/main.png" },
    horsepower: "177 hp",
    torque: "255 Nm",
    bootSpace: "330 L",
    length: "4330 mm",
    width: "1800 mm",
    airbags: 6,
    abs: true,
    fuelTankCapacity: "50 L",
    acceleration: "9.0 s",
  },
  {
    make: "Toyota",
    model: "Vios",
    year: 2023,
    fuel: "petrol",
    transmission: "Automatic",
    seats: 5,
    class: "sedan",
    fuelEconomy: "5.9 L/100 km",
    drive: "fwd",
    images: { main: "/cars/toyota-vios/main.png" },
    horsepower: "107 hp",
    torque: "140 Nm",
    bootSpace: "506 L",
    length: "4425 mm",
    width: "1730 mm",
    airbags: 2,
    abs: true,
    fuelTankCapacity: "42 L",
    acceleration: "11.5 s",
  },
  {
    make: "Toyota",
    model: "Corolla",
    year: 2022,
    fuel: "petrol",
    transmission: "Automatic",
    seats: 5,
    class: "sedan",
    fuelEconomy: "6.0 L/100 km",
    drive: "fwd",
    images: { main: "/cars/toyota-corolla/main.png" },
    horsepower: "112 hp",
    torque: "140 Nm",
    bootSpace: "470 L",
    length: "4630 mm",
    width: "1780 mm",
    airbags: 4,
    abs: true,
    fuelTankCapacity: "43 L",
    acceleration: "11.0 s",
  },
  {
    make: "Honda",
    model: "Civic",
    year: 2022,
    fuel: "petrol",
    transmission: "Automatic",
    seats: 5,
    class: "sedan",
    fuelEconomy: "6.2 L/100 km",
    drive: "fwd",
    images: { main: "/cars/honda-civic/main.png" },
    horsepower: "120 hp",
    torque: "145 Nm",
    bootSpace: "519 L",
    length: "4656 mm",
    width: "1799 mm",
    airbags: 4,
    abs: true,
    fuelTankCapacity: "47 L",
    acceleration: "10.5 s",
  },

  {
    make: "Honda",
    model: "HR-V",
    year: 2022,
    fuel: "petrol",
    transmission: "Automatic",
    seats: 5,
    class: "suv",
    fuelEconomy: "7.2 L/100 km",
    drive: "fwd",
    images: { main: "/cars/honda-hrv/main.png" },
    horsepower: "141 hp",
    torque: "172 Nm",
    bootSpace: "437 L",
    length: "4330 mm",
    width: "1790 mm",
    airbags: 4,
    abs: true,
    fuelTankCapacity: "50 L",
    acceleration: "10.0 s",
  },
  {
    make: "Mazda",
    model: "CX-5",
    year: 2023,
    fuel: "petrol",
    transmission: "Automatic",
    seats: 5,
    class: "suv",
    fuelEconomy: "7.2 L/100 km",
    drive: "fwd",
    images: { main: "/cars/mazda-cx5/main.png" },
    horsepower: "156 hp",
    torque: "200 Nm",
    bootSpace: "505 L",
    length: "4550 mm",
    width: "1840 mm",
    airbags: 6,
    abs: true,
    fuelTankCapacity: "55 L",
    acceleration: "9.2 s",
  },
  {
    make: "Mazda",
    model: "3 Hatchback",
    year: 2023,
    fuel: "petrol",
    transmission: "Automatic",
    seats: 5,
    class: "hatchback",
    fuelEconomy: "6.2 L/100 km",
    drive: "fwd",
    images: { main: "/cars/mazda-3-hatchback/main.png" },
    horsepower: "120 hp",
    torque: "150 Nm",
    bootSpace: "295 L",
    length: "4460 mm",
    width: "1795 mm",
    airbags: 4,
    abs: true,
    fuelTankCapacity: "51 L",
    acceleration: "10.8 s",
  },
  {
    make: "Honda",
    model: "City",
    year: 2022,
    fuel: "petrol",
    transmission: "Automatic",
    seats: 5,
    class: "sedan",
    fuelEconomy: "5.8 L/100 km",
    drive: "fwd",
    images: { main: "/cars/honda-city/main.png" },
    horsepower: "120 hp",
    torque: "145 Nm",
    bootSpace: "506 L",
    length: "4550 mm",
    width: "1748 mm",
    airbags: 4,
    abs: true,
    fuelTankCapacity: "45 L",
    acceleration: "10.5 s",
  },
  {
    make: "Volkswagen",
    model: "Tiguan",
    year: 2023,
    fuel: "petrol",
    transmission: "Automatic",
    seats: 5,
    class: "suv",
    fuelEconomy: "7.8 L/100 km",
    drive: "awd",
    images: { main: "/cars/volkswagen-tiguan/main.png" },
    horsepower: "150 hp",
    torque: "250 Nm",
    bootSpace: "615 L",
    length: "4501 mm",
    width: "1839 mm",
    airbags: 6,
    abs: true,
    fuelTankCapacity: "58 L",
    acceleration: "9.0 s",
  },
  {
    make: "BMW",
    model: "3 Series",
    year: 2023,
    fuel: "petrol",
    transmission: "Automatic",
    seats: 5,
    class: "sedan",
    fuelEconomy: "5.5 L/100 km",
    drive: "rwd",
    images: { main: "/cars/bmw-3series/main.png" },
    horsepower: "255 hp",
    torque: "400 Nm",
    bootSpace: "480 L",
    length: "4709 mm",
    width: "1827 mm",
    airbags: 6,
    abs: true,
    fuelTankCapacity: "60 L",
    acceleration: "5.8 s",
  },
  {
    make: "Mercedes",
    model: "C-Class",
    year: 2022,
    fuel: "petrol",
    transmission: "Automatic",
    seats: 5,
    class: "sedan",
    fuelEconomy: "5.3 L/100 km",
    drive: "rwd",
    images: { main: "/cars/mercedes-c/main.png" },
    horsepower: "255 hp",
    torque: "400 Nm",
    bootSpace: "455 L",
    length: "4686 mm",
    width: "1810 mm",
    airbags: 6,
    abs: true,
    fuelTankCapacity: "66 L",
    acceleration: "6.0 s",
  },
  {
    make: "BYD",
    model: "Seal",
    year: 2025,
    fuel: "Electric",
    transmission: "Automatic",
    seats: 5,
    class: "sedan",
    fuelEconomy: "16 kWh/100 km",
    drive: "awd",
    images: { main: "/cars/byd-seal/main.png" },
    horsepower: "350 hp",
    torque: "600 Nm",
    bootSpace: "450 L",
    length: "4700 mm",
    width: "1850 mm",
    airbags: 6,
    abs: true,
    fuelTankCapacity: "–",
    acceleration: "4.8 s",
  },

  {
    make: "Proton",
    model: "EMAS7",
    year: 2025,
    fuel: "Electric",
    transmission: "Automatic",
    seats: 7,
    class: "suv",
    fuelEconomy: "18 kWh/100 km",
    drive: "fwd",
    images: { main: "/cars/proton-emas7/main.png" },
    horsepower: "300 hp",
    torque: "500 Nm",
    bootSpace: "550 L",
    length: "4900 mm",
    width: "1900 mm",
    airbags: 6,
    abs: true,
    fuelTankCapacity: "–",
    acceleration: "5.2 s",
  },
];
