export interface Car {
  make: string;
  model: string;
  year: number;
  fuel: string;
  transmission: string;
  seats: number;
  image: string;
  class: "sedan" | "suv" | "hatchback" | "electric";
  city_kmpl: number;
  highway_kmpl: number;
  combined_kmpl: number;
  drive: "fwd" | "rwd" | "awd";
}

export const cars: Car[] = [
  {
    make: "Perodua",
    model: "Myvi",
    year: 2022,
    fuel: "petrol",
    transmission: "Automatic",
    seats: 5,
    image: "/cars/perodua-myvi.png",
    class: "hatchback",
    city_kmpl: 9.0,
    combined_kmpl: 7.6,
    highway_kmpl: 11.2,
    drive: "fwd",
  },
  {
    make: "Proton",
    model: "Persona",
    year: 2021,
    fuel: "petrol",
    transmission: "Automatic",
    seats: 5,
    image: "/cars/proton-persona.png",
    class: "sedan",
    city_kmpl: 8.0,
    combined_kmpl: 6.8,
    highway_kmpl: 9.8,
    drive: "fwd",
  },
  {
    make: "Toyota",
    model: "Vios",
    year: 2023,
    fuel: "petrol",
    transmission: "Automatic",
    seats: 5,
    image: "/cars/toyota-vios.png",
    class: "sedan",
    city_kmpl: 9.3,
    combined_kmpl: 7.8,
    highway_kmpl: 10.5,
    drive: "fwd",
  },
  {
    make: "Honda",
    model: "Civic",
    year: 2022,
    fuel: "petrol",
    transmission: "Automatic",
    seats: 5,
    image: "/cars/honda-civic.png",
    class: "sedan",
    city_kmpl: 9.8,
    combined_kmpl: 8.5,
    highway_kmpl: 11.5,
    drive: "fwd",
  },
  {
    make: "Toyota",
    model: "Corolla",
    year: 2022,
    fuel: "petrol",
    transmission: "Automatic",
    seats: 5,
    image: "/cars/toyota-corolla.png",
    class: "sedan",
    city_kmpl: 9.5,
    combined_kmpl: 8.0,
    highway_kmpl: 11.0,
    drive: "fwd",
  },
  {
    make: "Nissan",
    model: "Almera",
    year: 2023,
    fuel: "petrol",
    transmission: "Automatic",
    seats: 5,
    image: "/cars/nissan-almera.png",
    class: "sedan",
    city_kmpl: 9.0,
    combined_kmpl: 7.5,
    highway_kmpl: 10.8,
    drive: "fwd",
  },
  {
    make: "Honda",
    model: "HR-V",
    year: 2022,
    fuel: "petrol",
    transmission: "Automatic",
    seats: 5,
    image: "/cars/honda-hrv.png",
    class: "suv",
    city_kmpl: 7.5,
    combined_kmpl: 6.8,
    highway_kmpl: 9.0,
    drive: "fwd",
  },
  {
    make: "Toyota",
    model: "RAV4",
    year: 2023,
    fuel: "petrol",
    transmission: "Automatic",
    seats: 5,
    image: "/cars/toyota-rav4.png",
    class: "suv",
    city_kmpl: 7.2,
    combined_kmpl: 6.5,
    highway_kmpl: 8.9,
    drive: "awd",
  },
  {
    make: "BMW",
    model: "3 Series",
    year: 2023,
    fuel: "petrol",
    transmission: "Automatic",
    seats: 5,
    image: "/cars/bmw-3series.png",
    class: "sedan",
    city_kmpl: 5.9,
    combined_kmpl: 5.3,
    highway_kmpl: 6.8,
    drive: "rwd",
  },
  {
    make: "Mercedes",
    model: "C-Class",
    year: 2022,
    fuel: "petrol",
    transmission: "Automatic",
    seats: 5,
    image: "/cars/mercedes-c.png",
    class: "sedan",
    city_kmpl: 5.5,
    combined_kmpl: 5.0,
    highway_kmpl: 6.5,
    drive: "rwd",
  },
];
